### ISSUE TITLE
Does it work even if ESP32 pins are 3.3V only?

### ISSUE THREAD

**Issue by marcomac01** [Francesco-Mecatti/IBM-Model-F-XT-Keyboard-ESP32#1]
Hello, i was wondering if there are any risks in wiring the keyboard directly to the esp pins. As far as i know they can handle signals of 3.3V. If i could wire it without logic converters that'd be amazing (i would not have to wait for them to be shipped). 
Fantastico progetto, Francesco :)

**Comment by mc-cat-tty** [comment]
Ciao Marco, è da tanto che non metto mano a questo progetto, provo ad aiutarti il più possibile

Sebbene sia sconsigliato, sembra che i pin dell'ESP32 siano tolleranti ai 5V, a patto che la corrente entrante nel buffer di lettura sia bassa (come in questo caso). Dalla mia esperienza, l'ESP è incredibilmente robusto a "maltrattamenti" elettronici; ma sicuramente se vuoi fare un lavoro pulito e duraturo ti conviene aggiungere i level shifter.

Infine, ti segnalo che ti potrebbe capitare di ritrovarti con tasti "bloccati" (se viene perso l'evento di release) o poco reattivi (se viene perso l'evento di pressione). Se dovessi riscrivere questo pezzo di codice ora, userei un approccio differente: al posto di avere un callback che in modo sincrono esegue una transizione della macchina a stati e gestisce l'invio dell'evento tramite BLE, dividerei la logica in una callback che gestisca la FSM, più un task - pinnato al secondo core - che si occupi dell'invio degli eventi con BLE, comunicanti mediante una coda sincronizzata. In questo modo, l'invio con BLE, che suppongo sia l'origine del rallentamento in quanto bloccante, non impatterebbe sulla FSM, evitando che vengano persi cicli di clock. A questo punto il riconoscimento di un carattere da parte della procedura di callback diventerebbe semplicemente l'invio dell'evento sulla coda; mentre l'altro task si occuperebbe solamente di consumare i caratteri e inviarli.

Se ti interessa provare a lavorarci, FreeRTOS fornisce tutti gli strumenti necessari per l'implementazione che ho descritto sopra; e se poi dovesse funzionare, qualsiasi contribuzione è benvenuta.

------------------

Hello Marco, it's been a while since I started this project.

Although being discouraged, it looks like ESP32's pins are 5V-tolerant, as long as the current fed to the buffer is low (like in this scenario). From my experience, the ESP is amazingly robust and is able to withstand much worse voltage and current spikes. In order to make a more last-longing and clean design, I would suggest to add level-shifters anyway.

Lastly, keep in mind that there may be cases in which keys get stuck in pressed or released state. If I had to refactor the code now, I would choose a different approach: instead of having a huge callback function that synchronously triggers a transition of the FSM and also manages the interaction with the BLE connection, I would split up the logic so that the FSM is managed by the callback, while the BLE interaction is managed by a different task - pinned to the second core - that receives characters by a synchronized queue. This way, BLE's send function, which probably causes the unresponsive behaviour of that piece of software, would not impact the FSM, avoiding to skip clock cycles.

Take a look at FreeRTOS, which provides all the means to implement the aforementioned design; every contribution is welcome.

**Comment by marcomac01** [comment]
Capisco, effettivamente sembra avere più senso il nuovo approccio. Penso che proverò a giochicchiare quando avrò un pochino di tempo libero. Intanto ti ringrazio tanto per la risposta e la gentilezza. 
___________________
I understand, the new approach actually seems to make more sense. I think I'll try playing around when I have a little free time. In the meantime, thank you so much for your response and kindness.
